# Generated by Django 5.0.2 on 2024-02-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_alter_contact_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "city",
                    models.CharField(
                        choices=[("ALG", "Alger"), ("ORN", "Oran"), ("ANB", "Annaba")],
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.company"
            ),
        ),
    ]
