# Generated by Django 5.0.2 on 2024-02-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_company_alter_contact_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(
                choices=[("Alger", "Alger"), ("Oran", "Oran"), ("Annaba", "Annaba")],
                max_length=25,
            ),
        ),
    ]
