# Generated by Django 5.0.2 on 2024-02-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0004_alter_company_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Previous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous", models.URLField()),
            ],
        ),
    ]
