# Generated by Django 5.0.2 on 2024-02-20 22:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0007_alter_previous_previous"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("RFQ", "Rfq"),
                            ("Offer", "Offer"),
                            ("Negotiation", "Nego"),
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                        ],
                        max_length=11,
                    ),
                ),
                ("amount", models.FloatField(default=0)),
                ("number", models.CharField(max_length=15)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.contact"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Previous",
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "compagnies"},
        ),
    ]
